### ISSUE TITLE
Reduce some weight

### ISSUE THREAD

**Issue by cirocosta** [launchpad-project/cli#14]
Hey @henvic , just saw it on HN: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/ 

wdyt? Looks like an interesting tradeoff between startup time and weight. If we still hit `< 200ms` in startup time it's completely fine for a 6x+ weight loss.

> UPX is a portable, extendable, high-performance executable packer for several different executable formats. It achieves an excellent compression ratio and offers *very* fast decompression. Your executables suffer no memory overhead or other drawbacks for most of the formats supported, because of in-place decompression.

> <p align="right"><a href="http://linux.die.net/man/1/upx">http://linux.die.net/man/1/upx</a></p>

**Comment by henvic** [comment]
Hey Ciro,

currently our build is about 10MB.

I don't get how upx improved the binary so much since he claims to have used go 1.6.1 and since 1.6 upx (as stated on the own project repo) shouldn't help since improvements where made to the Go build tool itself.

Some tweaks we better stay away from (e.g., the ones that kill debugging features).

Go 1.7 also promises several improvements, btw.

**Comment by henvic** [comment]
Oh, pardon me.

Actually goupx is what is not anymore necessary for using... uh, upx.

https://github.com/pwaller/goupx

**Comment by igorspasic** [comment]
Hey guys, don't bother this much about this now, this is optimization which we can done later.

**Comment by henvic** [comment]
Hey Igor, don't worry!

> We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.
~ Donald Knuth


Is on the bottom of my [page](http://henvic.github.io/) ever since :)

**Comment by henvic** [comment]
Closing this for now.

When time comes, will try compressing the package with goupx / upx to see if it is worth to add this step to the build process, but won't play with stripping binaries. Stripping go binaries might lead to undefined results. See [docker's PACKAGERS.md Stripping binaries section](https://github.com/docker/docker/blob/2a95488f7843a773de2b541a47d9b971a635bfff/project/PACKAGERS.md#stripping-binaries).
